# Generated by Django 5.2.4 on 2025-08-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_at_twitter', models.DateTimeField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('profile_banner_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_profile', to='accounts.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('tweet_url', models.URLField(blank=True)),
                ('text', models.CharField(max_length=280)),
                ('has_media', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=False)),
                ('has_gif', models.BooleanField(default=False)),
                ('has_poll', models.BooleanField(default=False)),
                ('is_retweet', models.BooleanField(default=False)),
                ('is_quote_tweet', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('retweeted_tweet_id', models.CharField(blank=True, max_length=100)),
                ('quoted_tweet_id', models.CharField(blank=True, max_length=100)),
                ('replied_to_tweet_id', models.CharField(blank=True, max_length=100)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('quote_count', models.IntegerField(default=0)),
                ('impression_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='accounts.socialmediaaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['social_account', 'published_at'], name='twitter_twe_social__c8ad04_idx'), models.Index(fields=['tweet_id'], name='twitter_twe_tweet_i_8aba88_idx'), models.Index(fields=['is_retweet', 'is_quote_tweet', 'is_reply'], name='twitter_twe_is_retw_1832a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwitterFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweet_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(blank=True)),
                ('followed_at', models.DateTimeField()),
                ('unfollowed_at', models.DateTimeField(blank=True, null=True)),
                ('is_currently_following', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_followers', to='accounts.socialmediaaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['social_account', 'followed_at'], name='twitter_twi_social__8626f8_idx'), models.Index(fields=['is_currently_following'], name='twitter_twi_is_curr_2e548e_idx')],
                'unique_together': {('social_account', 'follower_id')},
            },
        ),
        migrations.CreateModel(
            name='TwitterHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('usage_count', models.IntegerField(default=1)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_engagements', models.IntegerField(default=0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('best_performing_tweet_id', models.CharField(blank=True, max_length=100)),
                ('first_used', models.DateTimeField()),
                ('last_used', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_hashtags', to='accounts.socialmediaaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['hashtag'], name='twitter_twi_hashtag_a5f93b_idx'), models.Index(fields=['usage_count'], name='twitter_twi_usage_c_064d3d_idx')],
                'unique_together': {('social_account', 'hashtag')},
            },
        ),
    ]
