# Generated by Django 5.2.4 on 2025-08-02 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Error')], default='active', max_length=10)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_state', models.CharField(blank=True, max_length=255)),
                ('code_verifier', models.CharField(blank=True, max_length=255)),
                ('redirect_uri', models.URLField(blank=True)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_data', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_data', to='accounts.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True)),
                ('rate_limit_reset', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='accounts.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('likes_received', models.IntegerField(default=0)),
                ('comments_received', models.IntegerField(default=0)),
                ('shares_received', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('posts_published', models.IntegerField(default=0)),
                ('likes_given', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('followers_lost', models.IntegerField(default=0)),
                ('following_gained', models.IntegerField(default=0)),
                ('following_lost', models.IntegerField(default=0)),
                ('custom_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.socialmediaaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['user', 'platform'], name='accounts_so_user_id_1ef326_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['status'], name='accounts_so_status_bf4560_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['last_sync'], name='accounts_so_last_sy_30388c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('user', 'platform', 'platform_user_id')},
        ),
        migrations.AddIndex(
            model_name='sessiondata',
            index=models.Index(fields=['user', 'expires_at'], name='accounts_se_user_id_22572f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiondata',
            index=models.Index(fields=['oauth_state'], name='accounts_se_oauth_s_e5813a_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ap_user_id_30caf9_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['social_account', 'created_at'], name='accounts_ap_social__3560d6_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['endpoint', 'created_at'], name='accounts_ap_endpoin_cd5121_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user', 'date'], name='accounts_us_user_id_66b36b_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['social_account', 'date'], name='accounts_us_social__96c002_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranalytics',
            unique_together={('social_account', 'date')},
        ),
    ]
