# Generated by Django 5.2.4 on 2025-08-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(blank=True, max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('public_profile_url', models.URLField(blank=True)),
                ('connection_count', models.IntegerField(default=0)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('background_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to='accounts.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(blank=True, max_length=220)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('connected_at', models.DateTimeField()),
                ('connection_type', models.CharField(default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_connections', to='accounts.socialmediaaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['social_account', 'connected_at'], name='linkedIn_li_social__795f5a_idx')],
                'unique_together': {('social_account', 'connection_id')},
            },
        ),
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('post_url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('has_image', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_document', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('impression_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('is_shared', models.BooleanField(default=False)),
                ('original_post_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_posts', to='accounts.socialmediaaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['social_account', 'published_at'], name='linkedIn_li_social__bfa30b_idx'), models.Index(fields=['post_id'], name='linkedIn_li_post_id_82f32d_idx')],
            },
        ),
    ]
